### ISSUE TITLE
feat(golang): Improve Go syntax highlighting

### ISSUE THREAD

**Issue by sleeping-barber** [jsit/toast.vim#10]
Hej @jsit 

I just stumbled upon your theme and it is exactly I was looking for (light theme but easy on my eyes). Thinking about using it for my productive setup (iTerm, tmux, vim) I encountered that the syntax highlighting looks boring to me when it comes to Go (I will append some screenshots later). 

If you could maybe mention some articles, tutorials, etc to read about highlighting in vim (I never touched the configuration in this depth so far), I would be happy to contribute some improvements for this theme in this regard.

Cheers!

**Comment by sleeping-barber** [comment]
Example: https://github.com/ThreeDotsLabs/watermill/blob/master/log.go

![Screenshot 2021-05-17 at 16 56 47](https://user-images.githubusercontent.com/10873365/118510114-f1ebae80-b730-11eb-9e8e-4b6ea5e892ef.png)

... calls to a function could have again some highlighting and somehow this doesn't look like `toast` to me after seeing the example of https://github.com/vim/vim/blob/master/runtime/syntax/syncolor.vim in the README :)

**Comment by jsit** [comment]
HI @sleeping-barber -- I'm trying not to add any language-specific stuff to this colorscheme, that should be kept to the syntax files in my opinion.

I'd try [this Go syntax plugin](https://github.com/fatih/vim-go), which seems to be popular.
