### ISSUE TITLE
Not getting the correct colors

### ISSUE THREAD

**Issue by prandelicious** [jsit/toast.vim#2]
Hi!

I'm on a Mac and not getting the expected colors.

![image](https://user-images.githubusercontent.com/5356451/97134351-fc8c2980-1787-11eb-862e-c4cb9c365d69.png)

Loading this via Plug:
`Plug 'jsit/toast.vim'`

Here's the relevant settings:
`
set t_Co=256
set bg=dark
colorscheme toast
`

**Comment by jsit** [comment]
Thanks for the report. Hm that's odd, I can't reproduce with `vim --clean`. Is there possibly something else in your `.vimrc` that's causing this?

**Comment by prandelicious** [comment]
Ran vim with `vim --clean` and manually loaded toast.vim:
![image](https://user-images.githubusercontent.com/5356451/97267225-c8d30180-1864-11eb-9e68-726154da9b96.png)

**Comment by jsit** [comment]
Hi interesting. What version of Vim, and what terminal emulator?

**Comment by prandelicious** [comment]
Vim version: 8.2
Terminal emulator: iTerm2

**Comment by jsit** [comment]
Hm I'm really baffled, sorry. I'm also using iTerm2 and Vim 8.2. Can you try in Terminal.app and see if you have the same issue? I wonder if it's a setting in iTerm that's causing it.

**Comment by jsit** [comment]
@prandelicious Are you still seeing this issue? Can you try creating a new Profile in iTerm and seeing if you get the same issue? Are you getting it in Terminal.app too?

**Comment by prandelicious** [comment]
I switched machines. Didn't bother to find out what was wrong with the old machine. Now it's working perfectly! Thanks for creating this awesome color scheme!
