### ISSUE TITLE
switching to this color scheme will move the cursor

### ISSUE THREAD

**Issue by jdhao** [jsit/toast.vim#7]
I installed several different color themes. I find that when I change to this colorscheme using command `:color toast`, the cursor will be moved to the first line of the buffer, which is really annoying.

To verify, use the following minimal config:

```vim
set runtimepath+=/path/to/toast.vim
```

Open neovim with:

```bash
nvim -u minimal.vim test.py
```

Put the cursor on other lines other than first line, active this colorscheme: `:color toast`.  The cursor will be moved to the first line.

**Comment by jdhao** [comment]
I think I have found the root cause of this issue. In [this line](https://github.com/jsit/toast.vim/blob/master/colors/toast.vim#L298), you use the following command:

```vim
exec s:hl("Type", s:type, "", "NONE")
```

which will first evaluate the result of `s:hl("Type", s:type, "", "NONE")`. But inside function `s:hl()`, you are execute some command. So the return value of this function will be 0 (suppose that there is no error during the execution of the function).

Now you are actually running the following command:

```
exec 0
```

this command is equivalent to `:0`, and it will put the cursor in the first line of this buffer. May be you mean `call` instead of `exec`?

**Comment by jsit** [comment]
Closed
